### ISSUE TITLE
Invalid contract created

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neo3-boa#107]
The following contract compiles without errors, but creates an invalid contract
```python
def fact(f: int) -> int:
    if f <= 1:
        return 1
    return f * fact(f-1)


def main() -> int:
    return fact(57)
```

It generates the following script
```
b'5700017811b6260411407878119f34f2a0400c0139db2134e940'
```
**Root cause**

The first instruction (0x57) is `INITSLOT`. It tries to initialize the engines `arguments` Slot with 1 value (should be `57d` from `fact(57)`), except there is no value on the evaluation stack to initialize it with. What is missing is a `PUSHINT8 + 57d` before the `INITSLOT`. The correct script is
```
b'00395700017811b6260411407878119f34f2a0400c0139db2134e940'
```
and then it works as expected.

**Comment by lock9** [comment]
To investigate: Is the contract invalid, or is the contract being invoked incorrectly? 
Compile the smart contract, add 'public' annotation to the methods, and invoke it to verify if it works.

**Comment by ixje** [comment]
See my root cause analysis. The script generated is currently invalid. If the solution is adding a public annotation, then it should probably have failed to compile to begin with.

**Comment by meevee98** [comment]
Sorry for the late answer.
Can you provide the manifest generated with the compilation?

Now, the ``main`` method doesn't need to be the first method converted in the bytecode.
 If ``main``'s offset is set to 0, so the script is indeed invalid, but if not then the execution should start in the given offset.

**Comment by ixje** [comment]
I don't remember which `boa` version I used to create this. I'd say if you can compile the contract with the latest `boa` version and it doesn't crash or cause a `FAULT` VMState then we can consider it resolved

**Comment by jseagrave21** [comment]
@meevee98 I know you are assigned to this but I was tinkering to see if I could help. I was able to compile the contract without errors, but I am unsure now what tool we are using to test the contract. I used `neo3-boa 0.6.1`.

**Comment by ixje** [comment]
This issue is still present in boa `0.6.1` and the solution is still the same as reported before. Adding a `@public` annotation to `def main()` does not matter, the generated code is still wrong.

```python
from boa3.boa3 import Boa3
from neo3 import vm
path = 'path_to_the_contract.py'
output = Boa3.compile(path)

engine = vm.ExecutionEngine()
# wrong
engine.load_script(vm.Script(output))
# correct
# engine.load_script(vm.Script(b'\x00\x39' + output))
assert engine.execute() == vm.VMState.HALT
```

**Comment by ixje** [comment]
@meevee98 ping

**Comment by meevee98** [comment]
I tried running this using the TestEngine in the same way we use it for the unit tests and it's running as expected.
https://github.com/CityOfZion/neo3-boa/blob/a5a367b180467ddf9697c7fc2fbc4dd753b0befa/boa3_test/tests/test_file_generation.py#L474-L488



> This issue is still present in boa `0.6.1` and the solution is still the same as reported before. Adding a `@public` annotation to `def main()` does not matter, the generated code is still wrong.
> 
> ```python
> from boa3.boa3 import Boa3
> from neo3 import vm
> path = 'path_to_the_contract.py'
> output = Boa3.compile(path)
> 
> engine = vm.ExecutionEngine()
> # wrong
> engine.load_script(vm.Script(output))
> # correct
> # engine.load_script(vm.Script(b'\x00\x39' + output))
> assert engine.execute() == vm.VMState.HALT
> ```

I don't think the case is that it's generating an invalid contract, I think it can be those cases:
- The result from ``Boa3.compile()`` is the raw bytecode, not the encoded nef bytecode (but because of the commented line, this doesn't seem to be the case)
- ExecutionEngine is executing it wrongly because the manifest is not passed to it, so it has no access to the map that stores the offset of each function

**Comment by ixje** [comment]
Your manifest remark made me try this contract in stead (putting Main on top)
```python
def fact(f: int) -> int:
    if f <= 1:
        return 1
    return f * fact(f-1)


def main() -> int:
    return fact(57)
```
Now it works as expected. I thought that `Main()` would always be at offset 0, but apparently it is not. 
Is this something we can enforce if we detect a `main()`? Because that would make programmatic contract compiling/testing more straight forward than having to search for the offsets in the manifest.

**Comment by lock9** [comment]
Hello @ixje,
The main method is not required anymore. You should invoke your method directly.

**Comment by ixje** [comment]
I think it might be worth to hint NEO2 -> NEO3 developers that they should place their main at the top of the file if they don't want to rewrite their logic. While it's not needed anymore, a main _can_ still work and might help them transition faster (also possibly doesn't need backend reworking). Just a thought. 

I'll close this :)
