### ISSUE TITLE
True and False keywords are misbehaving when used in method returns

### ISSUE THREAD

**Issue by EdgeDLT** [CityOfZion/neo3-boa#1075]
Methods with a Boolean return type will compile but not deploy... sometimes.

Take a look at this.

```py
from boa3.builtin.compile_time import public

@public
def addition_checker(a: int, b: int, c: int) -> bool:
    if a + b == c:
        return True
    else:
        return False
```

This code compiles, but on deploy it gives `Neo.VM.BadScriptException: Exception of type 'Neo.VM.BadScriptException' was thrown.` in Neo Express.

Trying an alternate approach:

```py
@public
def addition_checker(a: int, b: int, c: int) -> bool:
    return a + b == c
```

Compiles, deploys, and invokes as expected. Seems to imply something wrong with `True` and `False`. 

One more to test it:

```py
@public
def addition_checker(a: int, b: int, c: int) -> bool:
    if a + b == c:
        return bool(1)
    else:
        return bool(0)

```

Also deploys and invokes correctly. Worth some investigating?

**Comment by ixje** [comment]
@EdgeDLT what version of boa are you using? 

Using `0.14` I cannot reproduce it. The assembly looks fine to me
```
INDEX    OPCODE      PARAMETER
0        INITSLOT    0 local, 3 arg    <<
3        LDARG0      
4        LDARG1      
5        ADD         
6        LDARG2      
7        NUMEQUAL    
8        JMPIFNOT    12 (4/04)
10       PUSHT       
11       RET         
12       PUSHF       
13       RET         
```

I can call the function fine using `neo-debugger`. 
![image](https://github.com/CityOfZion/neo3-boa/assets/6625537/28053bdf-81d0-468f-a8fe-5268702e284f)

In case that is bypassing the script check I also deployed it to neo-express (using the visual dev thing) and called the function without problems
![image](https://github.com/CityOfZion/neo3-boa/assets/6625537/da8dce52-5dd2-43c4-a55e-27891dc9c936)

**Comment by EdgeDLT** [comment]
Sorry for wasting your time @ixje, my Boa install was significantly outdated. Works fine reinstalled in a fresh environment. Also fixed another issue I was having yesterday... it appears I need more sleep.

**Comment by ixje** [comment]
> it appears I need more sleep.

No worries, story of my life ;)
