### ISSUE TITLE
v0.5 Release Banner

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neo3-boa#133]
Marketing release banner for v0.5.

Refer to #114 for features 

Tentative deliverable is end of october.

**Comment by J-G-W** [comment]
As an idea moving forward maybe we could just bullet the updates as in the illustration below:

![image](https://user-images.githubusercontent.com/36457062/96583163-38307a80-12d4-11eb-9914-bb1f91cafe98.png)

**Comment by lllwvlvwlll** [comment]
I'm good with this approach!

**Comment by lllwvlvwlll** [comment]
@J-G-W can we get a final for this?

**Comment by J-G-W** [comment]
@lllwvlvwlll Sent it to you in slack!
