### ISSUE TITLE
Single underscore for private variables

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neo3-boa#17]
Skimming through the code I found that double underscore seems to be used to indicate private variables, for example
https://github.com/CityOfZion/neo3-boa/blob/feeb7a600813232c46c2b9b41803b7a15f3f0f1b/boa3/compiler/codegenerator.py#L43-L45

While the intention is good, by Python convention a single underscore is used to indicate "private" variables. Double underscore variables applies name mangling and serve a very specific use-case. [Python docs](https://docs.python.org/3/tutorial/classes.html#private-variables)

Historically, my IDE of choice (PyCharm) has had trouble handling double underscore variables in debugging sessions. They've fixed this now but other IDE's might not have. 

I'd like to suggest to follow the general Python convention use single underscore `_` for private variables. Any thoughts?

**Comment by melanke** [comment]
Well, I don't mind changing to a single underscore, but with a shallow google search both recommendations, to use a single underscore and a double underscore. So I don't know if we really NEED to change that, since it can lead to problems. But, I don't know, what do you think?

**Comment by ixje** [comment]
Let's be pragmatic and verify that the major IDE's properly support
inspection of the double underscore variables during debugging. If so we
can keep it as is. I know PyCharm is ok. To verify:
* Visual studio code
* PyDev
* Atom?

**Comment by lock9** [comment]
Hello. We have verified that the code doesn't contain double underscores anymore. I'm closing this. Thanks.
