### ISSUE TITLE
Confusing error message if testengine is not installed

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neo3-boa#193]
**Summary or problem description**
I wanted to quickly look into an issue I reported some time ago (#107). What I previously did there was simply replace the smart contract code of an existing test and run the test. I upgraded from boa 0.0.2 or 0.0.3 (very old) to 0.6.1. Now running the test gives this confusing error

```
boa3_test.tests.test_classes.TestExecutionException.TestExecutionException: Expecting value: line 1 column 3 (char 2)
```
while debugging shows the problem is
````
Could not execute because the specified command or file was not found.
Possible reasons for this include:
  * You misspelled a built-in dotnet command.
  * You intended to execute a .NET Core program, but dotnet-/Users/erik/Documents/code/neo3-boa/Neo.TestEngine/Neo.TestEngine.dll does not exist.
  * You intended to run a global tool, but a dotnet-prefixed executable with this name could not be found on the PATH.
````
**Do you have any solution you want to propose?**
validate this path exists and throw a clear error message if not
https://github.com/CityOfZion/neo3-boa/blob/82ab1168f2c2e9817c34f997c81eb12cabf2ef6f/boa3_test/tests/test_classes/testengine.py#L16

**Where in the software does this update applies to?**
testing framework

**Comment by meevee98** [comment]
in #223 the shown error was changed with a custom message
can you validate it and if it's ok can we close this issue?

**Comment by ixje** [comment]
I can confirm #223 gives a useful error message 👍
