### ISSUE TITLE
Add TestEngine installation instructions

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neo3-boa#194]
**Summary or problem description**
The readme doesn't describe how to install the test engine. There is a section stating
```
Make sure you have installed MSVC v142 - Build tools VS 2019 C++ x64/x86 (v14.24). You can do this by installing Visual Studio 2019 and add C++ development features.
```

Which I'm going to assume is related to the test engine, but that's actually also unclear why anyone would need those packages as I can compile without any of those installed.

I genuinely do not know where to get the test engine from so I can run tests

**Do you have any solution you want to propose?**
Update the readme to improve the instructions on test requirements, installing the test engine and running the tests

**Where in the software does this update applies to?**
test framework

**Comment by meevee98** [comment]
We took a look at this and there were some dependencies in the requirements that weren't needed anymore. The C++ build tools was related to these dependencies.
Since we don't use it anymore, we removed it from the requirements and the readme (see #221)

**Comment by ixje** [comment]
Thanks for looking into it. I'll close this
