### ISSUE TITLE
[Feat] Automated release process

### ISSUE THREAD

**Issue by lllwvlvwlll** [CityOfZion/neo3-boa#22]
It would be great to have an automated workflow to handle the release of the project. I believe we can use a workflow in circleci as follows:
1) On a release tag, trigger additional jobs on a release workflow 
2) This workflow would have a job to push the release to test-pypi and wait for a manual approval before pushing to pypi

**Comment by lock9** [comment]
Hi @lllwvlvwlll , I think this is implemented. Can we close this? Thanks

**Comment by lllwvlvwlll** [comment]
Closed, thanks!
