### ISSUE TITLE
Log behaviour deviating from regular Python

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neo3-boa#29]
I think it is good to start tracking what deviations writing smart contracts with `neo3-boa` brings compared to regular Python code. This can either become a usage "Improvements TODO" list, or if not solvable it can serve as usage documentation.

1. Cannot re-assign variables to different types ([ref](https://github.com/CityOfZion/neo3-boa/pull/27))

**Comment by ixje** [comment]
There is a possibility for runtime errors when assigning `None` to a variable that is later changed to hold a type. There should be a low chance this happens, but it cannot be caught on compile time (yet), because `None` will be set to `Typing.Any`. It requires the future type tracking improvement that also solves point 1. (see the original issue post)

**Comment by meevee98** [comment]
When specifying the return type on function signature and not including a `return` statement, the compiler includes the return of the specified type default value instead of returning None, that's Python behavior ([ref](https://github.com/CityOfZion/neo3-boa/pull/38)).
