### ISSUE TITLE
Basic Smart Contract Project scaffold

### ISSUE THREAD

**Issue by lock9** [CityOfZion/neo3-boa#307]
Create a semi-empty smart contract, basic meta-tags (author, email), debugger integration file, and unit tests.

- Basic Meta Tags (storage, author, contact)
- Debugger file
- Unit test
- Folder structure: contracts/src contracts/tests, integration/src, integration/tests  (integration folder is used with Neo mamba)

It should ask the user for the smart contract name.

Example:
'neo3-boa init'
Project name: "My New Contract"
Add integration project? (y/n)

Result:
readme.md
.gitignore
contracts/src/my_new_contract.py
contracts/test/my_new_contract_test.py

If 'add integration project' is true, also add these files:
integration/src/my_new_contract_integration.py
integration/test/my_new_contract_integration_test.py

Please leave the integration files empty for now.

**Comment by ixje** [comment]
This is still in the documentation as of today
![image](https://user-images.githubusercontent.com/6625537/169959678-f43269b8-440a-4ff8-80f6-739e8cf1dff8.png)

We have a lot of examples. Can't we copy paste one of those in here? @lock9 @meevee98
