### ISSUE TITLE
 Implement exponentiation as a builtin method to neo3-boa

### ISSUE THREAD

**Issue by luc10921** [CityOfZion/neo3-boa#359]
**Summary or problem description**
 Neo added an [exponentiation opcode](https://github.com/shargon/neo-vm/blob/31ee7ee07d7441dbe307c8ab054aae900e6e5956/src/neo-vm/OpCode.cs#L683)

**Do you have any solution you want to propose?**
 Add it as a builtin

**Where in the software does this update applies to?**
 [Builtin methods](https://github.com/CityOfZion/neo3-boa/tree/development/boa3/model/builtin/method)

**Comment by ixje** [comment]
I think it would be good if there is a mapping not only for the built-in `pow()` but also for the expression `base ** exp`
