### ISSUE TITLE
simple README for boa3_test/examples

### ISSUE THREAD

**Issue by gsmachado** [CityOfZion/neo3-boa#387]
It would be nice if you could add a simple `README.md` file in the [boa3_test/examples](https://github.com/CityOfZion/neo3-boa/tree/development/boa3_test/examples) directory, briefly explaining the purpose of each smart contract example, and how to build/test them.

**Comment by thiagocbalducci** [comment]
Add details on how to build/test each smart contract example to the new README that was implemented by #387 for boa3_test/examples.
