### ISSUE TITLE
Analyze viability of implementing dict copy method with current OPCodes

### ISSUE THREAD

**Issue by thiagocbalducci** [CityOfZion/neo3-boa#530]
a = {1: '1', 2: '2', 3: '3'}
b = a.copy()

**Comment by luc10921** [comment]
Could not find a equivalent to `Opcode.PACK` and `Opcode.UNPACK` for dictionaries. Probably will need to create an `Opcode.NEWMAP` and use `Opcode.KEYS` and `Opcode.VALUES` and put the pair manually in the `NEWMAP`. Maybe `Opcode.MEMCPY` could be usefull, but I'm not too sure how exactly Buffer works. Asking for Neo to create a new Opcode is also an option.
