### ISSUE TITLE
Refactor visit_Call to clarify code

### ISSUE THREAD

**Issue by meevee98** [CityOfZion/neo3-boa#584]
**Summary or problem description**
As we use python's ast package to read the input and convert it to a syntax tree, some different structures that are written in similar ways are converted to the same syntax tree node object. This is the reason that some node visitors have very complex logic and are difficult to read.
We need to refactor those codes in order to make the code easier to read and maintain.

**Do you have any solution you want to propose?**
Refactor the `visit_Call` implementation on [ModuleAnalyser](https://github.com/CityOfZion/neo3-boa/blob/03cb4b6f9eeee618273c91f03b9d475fd600d2ba/boa3/analyser/moduleanalyser.py#L863-L908), [TypeAnalyser](https://github.com/CityOfZion/neo3-boa/blob/03cb4b6f9eeee618273c91f03b9d475fd600d2ba/boa3/analyser/typeanalyser.py#L989-L1202) and [CodeGeneratorVisitor](https://github.com/CityOfZion/neo3-boa/blob/03cb4b6f9eeee618273c91f03b9d475fd600d2ba/boa3/compiler/codegenerator/codegeneratorvisitor.py#L537-L609) to simplify the code reading for each different case that's converted to a call ast node. Include more comments through the code as well.

**Comment by melanke** [comment]
## Organizing the process

- if there is no attribute (attribute "obj.my_method()" or not: "my_method()")
    - get the callable
- if there is no attribute
    - get the callable
- preparation on builtin cases (methods implemented by python or neo-boa)
- preparation on class construction cases

- after all preparations, validate if it is a callable (throw compilation error if not and interrupt execution)

- validations when the attribute is a class (throw compilation errors and interrupt execution)

- if the callable is a neo-boa-event simply returns the success

- throws exception on not implemented cases (interrupt execution)

- validate/preparations about the amount of arguments (throw compilation errors and interrupt execution)
    - there is some cases when the builtin needs to reorder the arguments

- do a map of argument types

- validate on builtin cases (throw compilation errors and interrupt execution)
