### ISSUE TITLE
Custom python decorators with global functions without arguments

### ISSUE THREAD

**Issue by meevee98** [CityOfZion/neo3-boa#647]
See #574
> A very simple use case I can think of would be to implement something like that: 
> 
> ```python
> from boa3.builtin import CreateNewEvent, public
>                                                
> def onlyOwner(): 
>     # do owner check and abort if false                              
>     pass                                       
>                                                
> @onlyOwner                                     
> @public                                        
> def withdraw() -> bool:                        
>     pass                                       
> 
> ```

Only decorators that calls global or imported functions without arguments is going to be implemented in this issue

**Comment by luc10921** [comment]
It's not possible to create a decorator without a parameter
