### ISSUE TITLE
one of the policy filters failed

### ISSUE THREAD

**Issue by klesun** [CityOfZion/neo3-boa#692]
**Describe the bug**

**How to Reproduce**
1. Open the project, run '...'
2. Type '...' or do '...'
3. ...

**Expected behavior**
A clear and concise description of what you think it should happen.

**Screenshots**

**Platform:**
 - OS: [e.g. Windows 10 x64]
 - Version: [e.g. neo3-boa v0.4]
 - Python version: [e.g. Python 3.8]

**(Optional) Additional context**

However, if your issue does not fit these aforementioned criteria, or it can be understood in another manner, feel free to open it in a different format.

**Comment by lock9** [comment]
Closed due to lack of information. Feel free to reopen it, but please don't forget to fill the information we request on our template. Thanks.

**Comment by klesun** [comment]
oh, sorry, I realised it's not relevant halfway writing it, but possibly hit "save" by accident
