### ISSUE TITLE
Integrate with Neo Blockchain Toolkit to generate a Python smart contract template

### ISSUE THREAD

**Issue by meevee98** [CityOfZion/neo3-boa#698]
https://github.com/neo-project/neo-blockchain-toolkit

try to create a template smart contract with a default nep17 contract
https://github.com/CityOfZion/neo3-boa/blob/development/boa3_test/examples/nep17.py

**Comment by luc10921** [comment]
Implemented it on this commit:
https://github.com/ngdenterprise/neo3-visual-tracker/pull/118/commits/4bbdd95e9304da64b77a06771c08d17853289e13
