### ISSUE TITLE
UInt160, UInt256, ECPoint only accept int, not bytes

### ISSUE THREAD

**Issue by ixje** [CityOfZion/neo3-boa#735]
**Describe the bug**
Using
```
from boa3.builtin.type import UInt160, UInt256, ECPoint
```
Trying to instantiate any of these 3 types with `bytes` or `bytearray` values fails to compile. I get the error (ignore line number)
```
ERROR: 48:19 - Expected type 'int', 'int', got 'bytes', 'int' instead
```
Specifying an `int` does work. However, the classes are typed with `Union[bytes, int]` and should accept bytes. 

**How to Reproduce**
Try to compile a contract with 
```python
from boa3.builtin import public
from boa3.builtin.type import UInt160, UInt256, ECPoint

@public
def func_no_arg_with_return_hash160() -> UInt160:
    return UInt160(b'\x01' * 20)

@public
def func_no_arg_with_return_hash256() -> UInt256:
    return UInt256(b'\x01' * 32)

@public
def func_no_arg_with_return_publickey() -> ECPoint:
    return ECPoint(b'\x01' * 33)
```
**Expected behavior**
I expect to be able to create these types with values other than all zero's (which is the behaviour is specifying an `int`)

**Platform:**
 - OS: OSX 11.6
 - Version: boa v0.10.0 (latest dev 507227631590f480b33aaa2eae10fd71f0d163dd)
 - Python version: 3.8.9

**Comment by meevee98** [comment]
From the error message, it looks like it is raised from the `*` operator and not from the constructors

**Comment by ixje** [comment]
It looks like you're right @meevee98 . It seems like boa doesn't understand `b'\x00' * 20` 
This doesn't work
```python
@public
def func_no_arg_with_return_publickey() -> ECPoint:
    x = b'\x00' * 33  # fails on this line
    return ECPoint(x)

```

but this does
```python
@public
def func_no_arg_with_return_publickey() -> ECPoint:
    return ECPoint(b'\x00\x01')
```

**Comment by ixje** [comment]
🎉
