### ISSUE TITLE
NEP-11 standard

### ISSUE THREAD

**Issue by NeoDashboard** [CityOfZion/neo3-boa#894]
Hey!
Seems like following the NEP-11 standard requires for properties method to have this signature:
`def properties(token_id: str) -> Dict[Any, Any]:`
But this lead to some issues integrating with GhostMarket that can be solved by changing to:
`def properties(token_id: ByteString) -> Dict[Any, Any]:`
Is there any reasons why It's **str** for now? Or can It be change as for now the only way to solve this is to remove `meta.supported_standards = ["NEP-11"]` and then add the standard manually on the manifest.
Let me know if I'm missing something :)

**Comment by meevee98** [comment]
Hi!
This is actually a bug that already was fixed by #871, but it isn't pushed to the PyPI yet.

Could you try to compile your smart contract using the development branch?

**Comment by NeoDashboard** [comment]
Oh thanks didn't build from sources :)
