### ISSUE TITLE
Invalid type for SETITEM: ByteString when assigning value at index in bytearray

### ISSUE THREAD

**Issue by hal0x2328** [CityOfZion/neo3-boa#903]
**Describe the bug**
An attempt to set a value at a given index of a bytearray fails at runtime with:
`boa3_test.tests.test_classes.TestExecutionException.TestExecutionException: Invalid type for SETITEM: ByteString`

**How to Reproduce**
Compile and invoke this contract:
```
from boa3.builtin import public

@public
def main() -> bytearray:
    a = bytearray(b'\x01\x02\x03\x04\x05\x06\x07\x08')
    a[0] = 0x02
    return a
```
This is basically the same code as in https://github.com/CityOfZion/neo3-boa/blob/master/boa3_test/test_sc/bytes_test/BytearraySetValue.py which also fails with the same error

**Expected behavior**
You should be able to set individual bytes within a bytestring by index, as in regular Python

**Platform:**
 - OS: OSX 12.4
 - Version: 0.11.2
 - Python version: 3.9.4

**Comment by nimmortal** [comment]
AFAIK, the exception occurs in NeoVM at [ExecutionEngine](https://github.com/neo-project/neo-vm/blob/5a11f4b4cad43a78410f070216a000779f838355/src/Neo.VM/ExecutionEngine.cs#L1298).
I have an assumption that the compiler uses a different type at the end where NeoVM expects `VMArray`.

**Comment by nimmortal** [comment]
@meevee98 cool, thank you for the fix. Any information on when the fix will be available with a new version? It's kinda blocking issue for us.
